name: Node CI

on: [push]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: clear cache
      run: npm cache verify
    - name: update npm
      run: npm install -g npm
    - name: install dependencies
      run: npm install
    - name: build vue project
      run: npm run build
    - name: show current dir
      run: |
        pwd
        ls
      shell: bash
    - name: execute deploy
      uses: crazy-max/ghaction-github-pages@v1.2.5
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
